import type { SourcePreviewItem } from '../../../../../shared/workspace-sources'
import type { WikiLinkResolver } from '@/components/app/markdown/plugins/wiki-links'
import { normalizeSourceFileKey, type SourcesPreviewLookup } from '@/components/app/sources/types'

export const WIKILINK_SCHEME = {
  dossier: 'dossier://',
  source: 'source://',
  lead: 'lead://',
  allegation: 'allegation://',
  finding: 'finding://',
  unresolved: 'wikilink://unresolved/',
  self: 'wikilink://self/',
} as const

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function isInsideWikiLink(text: string, index: number): boolean {
  const lastOpen = text.lastIndexOf('[[', index)
  const lastClose = text.lastIndexOf(']]', index)
  return lastOpen > lastClose
}

export function splitPdfMentionSuffix(raw: string): { base: string; pageSuffix: string } {
  const trimmed = raw.trim()
  const pageMatch = /\s+(p(?:ag(?:ina)?)?\.?\s*\d+)$/i.exec(trimmed)
  if (!pageMatch) {
    return { base: trimmed, pageSuffix: '' }
  }
  return {
    base: trimmed.slice(0, Math.max(0, pageMatch.index)).trim(),
    pageSuffix: pageMatch[1].trim(),
  }
}

export function resolveSourcePreviewFromWikiValue(
  value: string,
  sourcesLookup: SourcesPreviewLookup
): SourcePreviewItem | null {
  const { base } = splitPdfMentionSuffix(value)
  const normalized = normalizeSourceFileKey(base)
  if (!normalized) return null

  if (normalized.endsWith('.pdf')) {
    return sourcesLookup.byPdfFileKey.get(normalized) ?? null
  }

  return sourcesLookup.byPdfStemKey.get(normalized) ?? null
}

function cleanPdfCandidate(raw: string): string {
  return raw
    .trim()
    .replace(/^[\s"'“”‘’`*_([{-]+/u, '')
    .replace(/[\s"'“”‘’`*_)\]}.,;:!?]+$/u, '')
}

function resolvePdfLabelFromText(rawPdfMention: string, sourcesLookup: SourcesPreviewLookup): string | null {
  const trimmed = cleanPdfCandidate(rawPdfMention)
  if (!trimmed) return null

  const direct = resolveSourcePreviewFromWikiValue(trimmed, sourcesLookup)
  if (direct) return direct.fileName

  const words = trimmed.split(/\s+/).filter(Boolean)
  for (let start = 1; start < words.length; start += 1) {
    const candidate = cleanPdfCandidate(words.slice(start).join(' '))
    if (!candidate.toLowerCase().endsWith('.pdf')) continue
    const resolved = resolveSourcePreviewFromWikiValue(candidate, sourcesLookup)
    if (resolved) return resolved.fileName
  }

  return null
}

export function injectPdfMentionsAsWikiLinks(content: string, sourcesLookup: SourcesPreviewLookup): string {
  if (sourcesLookup.byPdfFileKey.size === 0 && sourcesLookup.byPdfStemKey.size === 0) {
    return content
  }

  const pattern = /([\p{L}\p{N}_\-./() ]+?\.pdf)(\s+(?:p(?:ag(?:ina)?)?\.?\s*\d+))?/giu

  return content.replace(pattern, (match, rawPdfMention: string, pageSuffix: string, offset: number, full: string) => {
    if (isInsideWikiLink(full, offset)) return match
    const label = resolvePdfLabelFromText(rawPdfMention, sourcesLookup)
    if (!label) return match
    const suffix = typeof pageSuffix === 'string' && pageSuffix.trim() ? ` ${pageSuffix.trim()}` : ''
    return `[[${label}${suffix}]]`
  })
}

function readResolutionHref(resolved: ReturnType<WikiLinkResolver>): string {
  return typeof resolved === 'string' ? resolved : resolved.href
}

export function injectDynamicBacklinks(
  content: string,
  resolver: WikiLinkResolver,
  currentDocumentPath?: string
): string {
  const placeholderPattern =
    /\((?:auto[-\s]*generated by renderer via backlinks|auto[-\s]*gerado pelo render via backlinks)\)/i
  if (!placeholderPattern.test(content)) {
    return content
  }

  const seen = new Set<string>()
  const backlinks: string[] = []
  const wikiPattern = /\[\[([^[\]]+)\]\]/g
  let match = wikiPattern.exec(content)
  while (match) {
    const value = match[1].trim()
    if (value && !seen.has(value)) {
      const resolution = resolver(value, { currentDocumentPath })
      const href = readResolutionHref(resolution)
      if (
        !href.startsWith(WIKILINK_SCHEME.unresolved) &&
        !href.startsWith(WIKILINK_SCHEME.self)
      ) {
        backlinks.push(`- [[${value}]]`)
        seen.add(value)
      }
    }
    match = wikiPattern.exec(content)
  }

  const replacement =
    backlinks.length > 0
      ? backlinks.join('\n')
      : '(No resolved connections yet)'

  return content.replace(placeholderPattern, replacement)
}

export function injectEntityMentionsAsWikiLinks(content: string, entityNames: string[]): string {
  const uniqueCandidates = Array.from(
    new Set(
      entityNames
        .map((name) => name.trim())
        .filter((name) => name.length >= 4 && !name.includes('[['))
    )
  ).sort((left, right) => right.length - left.length)

  if (!uniqueCandidates.length) return content

  let output = content
  for (const candidate of uniqueCandidates) {
    const pattern = new RegExp(`(^|[^\\p{L}\\p{N}_])((${escapeRegExp(candidate)}))(?![\\p{L}\\p{N}_])`, 'giu')
    output = output.replace(pattern, (match, prefix: string, value: string, _whole: string, offset: number, full: string) => {
      const valueStart = offset + prefix.length
      if (isInsideWikiLink(full, valueStart)) return match
      return `${prefix}[[${value}]]`
    })
  }

  return output
}
